version : "3.8"

services:
  db: 
    image: mysql:5.7
    container_name: db
    restart: "no"
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: ignite
    volumes:
      - my-db:/var/lib/mysql
    ports:
    - '3306:3306'
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8082:80'
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: mypassword

volumes:
  my-db: